#!/usr/bin/env node
/**
 * Build a single-file n8n Code node script by inlining the JS PDL library.
 *
 * Output: dist/n8n.js
 */

const fs = require('fs');
const path = require('path');

const repoRoot = path.join(__dirname, '..');
const libPath = path.join(repoRoot, 'packages/js/src/pdl.js');
const outPath = path.join(repoRoot, 'dist/n8n.js');

function readLib() {
  let src = fs.readFileSync(libPath, 'utf8');
  const idx = src.indexOf('module.exports');
  if (idx !== -1) {
    src = src.slice(0, idx);
  }
  return src.trim();
}

function build() {
  const libSrc = readLib();

const banner = `/* Auto-generated by scripts/build-n8n.js
 * Date: ${new Date().toISOString()}
 * Contains PDL JS library + n8n adapter.
 */`;

const configBlock = `// ===== PDL node config (inputs) =====
const pdlConfig = {
  data: $('Config').first().json.Data,
  template: $('Config').first().json.Template,
  headerIndentation: $('Config').first().json.HeaderIndentation || '#',
  dropFirstHeader: $('Config').first().json.DropFirstHeader || false,
  variables: $('Config').first().json.Variables || {},
  // Settings are defined in the library; override here if you need custom caps/prefixes.
};`;

const adapter = `
// ===== n8n adapter =====
const { render } = PDL_LIB;

const result = render(pdlConfig.template, pdlConfig.data, {
  headerIndentation: pdlConfig.headerIndentation,
  dropFirstHeader: pdlConfig.dropFirstHeader,
  variables: pdlConfig.variables,
});

return [
  {
    json: {
      Markdown: result.markdown,
      Stats: result.stats,
    },
  },
];
`;

  const bundle = `${banner}

${configBlock}

// ===== PDL library (inlined) =====
const PDL_LIB = (() => {
${libSrc}
  return { render, PDL, PDLParser, PostFormat, RenderStats };
})();

${adapter}
`;

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, bundle, 'utf8');
  console.log('Built', path.relative(repoRoot, outPath));
}

build();
