#!/usr/bin/env python3
"""Build a single-file Langflow component by inlining the Python PDL library.

Output: dist/langflow.py

Mirrors the structure of scripts/build-n8n.js, but uses Python so Langflow
users can easily inspect/adjust the build if needed.
"""

from __future__ import annotations

import datetime
import pathlib


REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
PDL_PATH = REPO_ROOT / "packages" / "py" / "pdl" / "pdl.py"
COMPONENT_PATH = REPO_ROOT / "adapters" / "langflow" / "langflow.py"
OUT_PATH = REPO_ROOT / "dist" / "langflow.py"


def read_text(path: pathlib.Path) -> str:
    return path.read_text(encoding="utf-8")


def build() -> None:
    pdl_src = read_text(PDL_PATH)
    component_src = read_text(COMPONENT_PATH)

    now_utc = datetime.datetime.now(datetime.timezone.utc).isoformat()
    banner = (
        "# Auto-generated by scripts/build-langflow.py\n"
        f"# Date: {now_utc}\n"
        "# Contains PDL Python library + Langflow adapter.\n\n"
    )

    bundle = banner + pdl_src.rstrip() + "\n\n" + component_src.lstrip()

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(bundle, encoding="utf-8")
    print("Built", OUT_PATH.relative_to(REPO_ROOT))


if __name__ == "__main__":
    build()
