#!/usr/bin/env node
/**
 * Build a browser-friendly PDL bundle.
 *
 * Output: dist/browser.js
 * Exposes a global `PDL` with { render, PDL, PDLParser, PostFormat, RenderStats }.
 */

const fs = require('fs');
const path = require('path');

const repoRoot = path.join(__dirname, '..');
const libPath = path.join(repoRoot, 'packages/js/src/pdl.js');
const outPath = path.join(repoRoot, 'dist/browser.js');

function readLibSource() {
  let src = fs.readFileSync(libPath, 'utf8');
  const idx = src.lastIndexOf('module.exports');
  if (idx !== -1) {
    src = src.slice(0, idx);
  }
  return src.trimEnd();
}

function build() {
  const libSrc = readLibSource();

  const banner = `/* Auto-generated by scripts/build-browser.js
 * Date: ${new Date().toISOString()}
 * Contains PDL JS library, exposed for browser environments.
 */`;

  const bundle = `${banner}

(function (global) {
const PDL_LIB = (() => {
${libSrc}

return { render, PDL, PDLParser, PostFormat, RenderStats };
})();

if (typeof module !== 'undefined' && module.exports) {
  module.exports = PDL_LIB;
}
if (global) {
  global.PDL = PDL_LIB;
}
})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);
`;

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, bundle, 'utf8');
  console.log('Built', path.relative(repoRoot, outPath));
}

build();
